name: CD - Deploy na EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/git-lab:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/git-lab:latest
