# Imagem base
FROM node:20

# Define o diretório de trabalho
WORKDIR /app

# Copia todos os arquivos do projeto para dentro da imagem
COPY . .

# Comando de teste (apenas imprime a versão do Node)
CMD ["node", "-v"]
