name: CD - Deploy App

on:
  push:
    branches: [ main ]
    paths:
      - 'app.js'
      - 'Dockerfile'

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t gabriel1304/node-app:latest .

      - name: Push para Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push gabriel1304/node-app:latest
