# .github/workflows/cd-app.yml

name: CD - Deploy App

on:
  push:
    branches:
      - main
    paths:
      - app.js
      - Dockerfile
      - .github/workflows/cd-app.yml

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da imagem Docker
        run: docker build -t app:latest .

      - name: Rodar container local (simulação de deploy)
        run: docker run -d -p 3000:3000 app:latest
