# .github/workflows/cd-ecs.yml

name: CD - Deploy ECS

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/cd-ecs.yml

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Inicializar Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Aplicar infraestrutura ECS
        working-directory: ./terraform
        run: terraform apply -auto-approve
