name: CD - Deploy local

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Pull da imagem
        run: docker pull ${{ secrets.DOCKER_USER }}/node-app:latest

      - name: Subir o container
        run: |
          docker stop node-app || true
          docker rm node-app || true
          docker run -d -p 3000:3000 --name node-app ${{ secrets.DOCKER_USER }}/node-app:latest
