name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/minha-imagem-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push da imagem para GHCR
        run: |
          docker push $IMAGE_NAME:latest
