name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/minha-imagem-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build e Push da imagem Docker
        run: |
          IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE:latest .
          docker push $IMAGE:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Criar arquivo da chave privada
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy na EC2
        run: |
          IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.GHCR_TOKEN }}
            docker pull $IMAGE:latest
            docker stop app || true && docker rm app || true
            docker run -d --name app -p 80:3000 $IMAGE:latest
          EOF
